// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.Infrastructure.Persistence;

#nullable disable

namespace WeatherApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108211439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("WeatherApp.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_envio");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expira_em");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("mensagem");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("titulo");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("Alerta__IDX");

                    b.ToTable("Alerta", (string)null);
                });

            modelBuilder.Entity("WeatherApp.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("Localizacao__IDX");

                    b.ToTable("Localizacao", (string)null);
                });

            modelBuilder.Entity("WeatherApp.Domain.Entities.WeatherReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("condition");

                    b.Property<double>("HumidityPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("humidity");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_hora");

                    b.Property<double>("Temperature")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("temp");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("temp_unit");

                    b.Property<double>("WindSpeedKmh")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("wind_speed");

                    b.Property<Guid>("id_localizacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("Clima__IDX");

                    b.HasIndex("id_localizacao");

                    b.ToTable("Clima", (string)null);
                });

            modelBuilder.Entity("WeatherApp.Domain.Entities.Location", b =>
                {
                    b.OwnsOne("WeatherApp.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("LocationId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Latitude")
                                .HasPrecision(8, 4)
                                .HasColumnType("REAL")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasPrecision(8, 4)
                                .HasColumnType("REAL")
                                .HasColumnName("longitude");

                            b1.HasKey("LocationId");

                            b1.ToTable("Localizacao");

                            b1.WithOwner()
                                .HasForeignKey("LocationId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("WeatherApp.Domain.Entities.WeatherReading", b =>
                {
                    b.HasOne("WeatherApp.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("id_localizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WeatherApp.Domain.ValueObjects.Probability", "PrecipitationProbability", b1 =>
                        {
                            b1.Property<Guid>("WeatherReadingId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasPrecision(6, 4)
                                .HasColumnType("REAL")
                                .HasColumnName("precip_prob");

                            b1.HasKey("WeatherReadingId");

                            b1.ToTable("Clima");

                            b1.WithOwner()
                                .HasForeignKey("WeatherReadingId");
                        });

                    b.Navigation("Location");

                    b.Navigation("PrecipitationProbability")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
